---

- hosts: all
  gather_facts: false
  tasks:
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          cluster: "vc.mk.io"
          datastore: "Datastore"
          folder: "test"
          
        name: test_vm1
        guest_OS: DEBIAN_8_64
        hardware_version: VMX_11
        memory:
          hot_add_enabled: true
          size_MiB: 1024
      register: _result
