---
- hosts: localhost
  tasks:
    
    - name: collect a list of the datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: my_datacenters
    - name: Build a list of all the clusters
      vmware.vmware_rest.vcenter_cluster_info:
      register: all_the_clusters
    - name: Retrieve details about the first cluster
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: "{{ all_the_clusters.value[0].cluster }}"
      register: my_cluster_info
    - name: Retrieve a list of all the datastores
      vmware.vmware_rest.vcenter_datastore_info:
        filter_names:
        - Datastore
      register: my_datastores
    - name: Set my_datastore
      set_fact:
         my_datastore: '{{ my_datastores.value|first }}'  
    - name: Build a list of all the folders
      vmware.vmware_rest.vcenter_folder_info:
      register: my_folders
    - name: Build a list of all the folders with the type VIRTUAL_MACHINE and called vm
      vmware.vmware_rest.vcenter_folder_info:
        filter_type: VIRTUAL_MACHINE
        filter_names:
          - test
      register: my_folders   
    - name: Set my_virtual_machine_folder
      set_fact:
        my_virtual_machine_folder: '{{ my_folders.value|first }}'


    - name: Look up the VM called test_vm1 in the inventory
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - bastion
      register: search_result

    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ search_result.value[0].vm }}'
      register: test_vm1_info
    - name: debug test_vm1_info
      debug:
        var: test_vm1_info

      
