---
- hosts: localhost
  tasks:
    - name: Retrieve a list of all the datastores
      vmware.vmware_rest.vcenter_datastore_info:
        filter_names:
        - Datastore
      register: my_datastores
    - name: Set my_datastore
      set_fact:
         my_datastore: '{{ my_datastores.value|first }}'  
    - name: Create a content library based on a DataStore
      vmware.vmware_rest.content_locallibrary:
        name: my_library_on_datastore
        description: automated
        publish_info:
          published: true
          authentication_method: NONE
        storage_backings:
        - datastore_id: "{{ my_datastore.datastore }}"
          type: DATASTORE
        state: present
      register: nfs_lib

    - name: debug info
      debug: 
        var: nfs_lib
        
