---
- hosts: localhost
  tasks:
    - name: List all Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: all_content_libraries
    - name: debug info
      debug: 
        var: all_content_libraries
    - name: Use the name to identify the right Content Library
      set_fact:
        nfs_lib: "{{ all_content_libraries.value | selectattr('name', 'equalto', 'test')|first }}"
        
    - name: debug info
      debug: 
        var: nfs_lib
        
