---
- hosts: localhost
  tasks:


    - name: List all Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: nfs_lib
    - name: debug info
      debug: 
        var: nfs_lib
    - name: Get the list of items of the NFS library
      vmware.vmware_rest.content_library_item_info:
        library_id: '{{ nfs_lib.id | selectattr('name', 'equalto', 'test')|first}}'
      register: lib_items    
    - name: debug info
      debug: 
        var: lib_items   
        
