---
- hosts: localhost
  tasks:
    - name: List all Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: nfs_lib
    - name: debug info
      debug: 
        var: nfs_lib
    - name: Use the name to identify the item
      set_fact:
        result: "{{ nfs_lib.id | selectattr('id')|first }}" 
        
    - name: debug info
      debug: 
        var: result 
        
