---
- hosts: localhost
  tasks:
    - name: List all Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: nfs_lib
    - name: debug info
      debug: 
        var: nfs_lib
    - name: Retrieve the local content library information based upon id check mode
      vmware.vmware_rest.content_locallibrary_info:
        library_id: '{{ nfs_lib.id }}'
      register: result
      check_mode: true    
    
    - name: debug info
      debug: 
        var: result 
        
