---
- hosts: localhost
  tasks:
    
    - name: collect a list of the filesystem
      vmware.vmware_rest.content_locallibrary:
      register: nfs_lib

    - name: debug info
      debug: 
        var: nfs_lib
        
