---
- hosts: localhost
  tasks:
    - name: Get My vCenter
      vmware.vmware_rest.vcenter_datacenter_info:
        vcenter_username: administrator@vsphere.local
        vcenter_password: Default!23
        vcenter_hostname: vc.mk.io
        vcenter_validate_certs: no
      register: r

    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          cluster: "vc.mk.io"
          datastore: "/DC1/Datastore"
          #folder: "/DC1/test/"
          
        name: test_vm1
        guest_OS: RHEL_8_64
        hardware_version: VMX_11
        memory:
          hot_add_enabled: true
          size_MiB: 1024
        cdroms:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: "[Datastore] rhel-8.6-x86_64-dvd.iso"  
      register: _result
